/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 .\radio.gltf 
*/
import React, { useContext, useEffect, useRef, useState, useMemo } from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'
import { LoopOnce } from 'three'
import { WebsocketContext } from '../../utilComponents/WebsocketProvider'
import { useAtom } from 'jotai'
import { radioHoverAtom } from '../../atoms/atoms'

export function Radio(props) {
  // 1. Získání 3D modelu a animací
  const group = useRef()
  const { scene, animations } = useGLTF('/models/radio/radio.gltf')
  const clone = useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes } = useGraph(clone) // materials nepoužíváme, ale můžeš přidat, pokud třeba měníš barvy
  const { actions } = useAnimations(animations, group)

  // 2. Global state a kontext
  const { data, send } = useContext(WebsocketContext)
  const [, setRadioHover] = useAtom(radioHoverAtom)

  // 3. Lokální stav rádia (synchronizovaný s BE)
  const [radioState, setRadioState] = useState({
    isPlaying: false,
    songPath: null
  })

  // 4. Audio reference (jedna instance, neničíme paměť)
  // Vytvoříme audio jen jednou a budeme měnit jeho src
  const audioRef = useRef(new Audio())

  // Inicializace hlasitosti
  useEffect(() => {
    audioRef.current.volume = 0.1
    // Cleanup při odchodu ze scény
    return () => {
      audioRef.current.pause()
      audioRef.current.src = ""
    }
  }, [])

  // ----------------------------------------------------------------
  // LOGIKA 1: Poslech dat z Webu (Synchronizace s Backendem)
  // ----------------------------------------------------------------
  useEffect(() => {
    if (!data) return

    // Pokud se někdo připojí a rádio už hraje, nebo přijde změna stavu rádia
    if (data.type === 'radio') {
      setRadioState({
        isPlaying: data.state,      // true/false
        songPath: data.songPath     // "/sounds/neco.mp3" nebo null
      })
    }
    // Pokud máš logiku pro 'join-room', která posílá aktuální stav rádia,
    // měl by backend poslat zprávu typu 'radio' hned po připojení, 
    // nebo sem přidej logiku pro data.type === 'join-room' podobně.
  }, [data])

  // ----------------------------------------------------------------
  // LOGIKA 2: Ovládání audia (Reakce na změnu radioState)
  // ----------------------------------------------------------------
  useEffect(() => {
    const audio = audioRef.current

    if (radioState.isPlaying && radioState.songPath) {
      // Pokud je zapnuto a máme cestu -> Načíst a hrát
      
      // Kontrola, jestli už nehraje to samé (aby se nerestartovalo při rejoinu)
      // Pokud URL obsahuje doménu, porovnáme koncovku nebo celou cestu
      const currentSrcPath = new URL(audio.src, window.location.href).pathname;
      if (currentSrcPath === radioState.songPath && !audio.paused) {
        return; 
      }

      audio.src = radioState.songPath
      audio.load()

      // "Skladba se musí nejdřív načíst a až pak se začne přehrávat"
      const handleCanPlay = () => {
        audio.play().catch(e => console.warn("Autoplay blocked or error:", e))
      }

      // Event listener pro načtení
      audio.addEventListener('canplaythrough', handleCanPlay, { once: true })

    } else {
      // Pokud je vypnuto -> Stop
      audio.pause()
      audio.currentTime = 0
    }

  }, [radioState])

  // ----------------------------------------------------------------
  // LOGIKA 3: Animace (Reakce na změnu radioState.isPlaying)
  // ----------------------------------------------------------------
  useEffect(() => {
    // Bezpečný reset animací
    const actionOn = actions['on']
    const actionOff = actions['off']

    if (!actionOn || !actionOff) return

    if (radioState.isPlaying) {
      // Zapínáme rádio
      actionOff.stop() // Zastav vypínací animaci
      
      actionOn.reset()
      actionOn.setLoop(LoopOnce)
      actionOn.clampWhenFinished = true
      actionOn.play()
    } else {
      // Vypínáme rádio
      // Poznámka: Pokud se načte stránka a rádio je vypnuté, možná nechceš přehrát animaci vypnutí,
      // ale jen nechat model ve výchozím stavu. Pokud ano, přidej podmínku "isMounted".
      actionOn.stop()
      
      actionOff.reset()
      actionOff.setLoop(LoopOnce)
      actionOff.clampWhenFinished = true
      actionOff.play()
    }
  }, [radioState.isPlaying, actions])

  // ----------------------------------------------------------------
  // Interakce uživatele
  // ----------------------------------------------------------------
  const handlePointerDown = (e) => {
    e.stopPropagation()
    
    // Pouze pošleme signál na BE. Neměníme lokální stav!
    // Čekáme, až BE pošle zprávu {"type": "radio", ...}, která triggeruje useEffect výše.
    const message = radioState.isPlaying 
      ? JSON.stringify({ type: "radio-off" })
      : JSON.stringify({ type: "radio-on" }) // Backend vybere song
    
    send(message)
  }

  const handlePointerEnter = () => {
    document.body.style.cursor = 'pointer'
    setRadioHover(true)
  }

  const handlePointerLeave = () => {
    document.body.style.cursor = 'auto'
    setRadioHover(false)
  }

  return (
    <group ref={group} {...props} dispose={null} 
      onPointerDown={handlePointerDown} 
      onPointerEnter={handlePointerEnter} 
      onPointerLeave={handlePointerLeave}
    >
      <group name="Armature" position={[-0.152, 0.162, -0.331]} rotation={[1.332, -0.041, 0.167]} scale={0.434}>
        <primitive object={nodes.Bone002} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/radio/radio.gltf') // Opravená cesta dle tvého kódu