/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 saloon.gltf 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Saloon(props) {
  const { nodes, materials } = useGLTF('/models/salonOutside/saloon.gltf')
  return (
    <group {...props} dispose={null}>

      <group position={[13.356, 1.591, 5.999]} rotation={[0, 0.194, 0]}>
        <mesh geometry={nodes.Cube003.geometry} material={materials['Material.030']} />
        <mesh geometry={nodes.Cube003_1.geometry} material={materials['Material.029']} />
        <mesh geometry={nodes.Cube003_2.geometry} material={materials['Material.031']} />
        <mesh geometry={nodes.Cube003_3.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Cube003_4.geometry} material={materials.Material} />
        <mesh geometry={nodes.Cube003_5.geometry} material={materials['Material.027']} />
        <mesh geometry={nodes.Cube003_6.geometry} material={materials['Material.028']} />
        <mesh geometry={nodes.Cube003_7.geometry} material={materials['Material.034']} />
        <mesh geometry={nodes.Cube003_8.geometry} material={materials['Material.035']} />
        <mesh geometry={nodes.Cube003_9.geometry} material={materials['Material.036']} />
        <mesh geometry={nodes.Cube003_10.geometry} material={materials['Material.037']} />
        <mesh geometry={nodes.Cube003_11.geometry} material={materials['Material.038']} />
        <mesh geometry={nodes.Cube003_12.geometry} material={materials['Material.040']} />
        <mesh geometry={nodes.Cube003_13.geometry} material={materials['Material.041']} />
        <mesh geometry={nodes.Cube003_14.geometry} material={materials['Material.042']} />
        <mesh geometry={nodes.Cube003_15.geometry} material={materials['Material.043']} />
      </group>
      <mesh geometry={nodes.Duck.geometry} material={materials['Material.001']} position={[13.448, 12.603, 0.909]} rotation={[1.571, -0.005, -1.766]} scale={1.685} />
      <mesh geometry={nodes.Duck001.geometry} material={materials['Material.001']} position={[13.488, 10.845, 1.115]} rotation={[1.571, -0.005, -1.766]} scale={1.685} />
      <mesh geometry={nodes.Duck002.geometry} material={materials['Material.001']} position={[13.367, 11.665, 0.066]} rotation={[1.571, -0.005, -1.766]} scale={1.913} />
    </group>
  )
}

useGLTF.preload('/saloon.gltf')
