/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 cardpack.gltf 
*/

import React from 'react'
import { Sphere } from '@react-three/drei'
import { EffectComposer, Bloom, ToneMapping } from '@react-three/postprocessing'

export function Sun() {
    return (
    <mesh position={[20, 60, -250]}>
        {/* <EffectComposer>
            <Bloom  intensity={0.4} blurPass={undefined} luminanceThreshold={0.1} luminanceSmoothing={0.2}/>
        </EffectComposer> */}
        <Sphere  args={[5, 32, 32]} />
        <meshStandardMaterial color="white" />
    </mesh>
  )
}
export default Sun;