/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 teren.gltf 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Teren(props) {
  const { nodes, materials } = useGLTF('/models/teren/teren.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[214.107, 0, 0]} rotation={[-1.571, 0.001, 0.008]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group position={[-543.247, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.cactus_3_cacturs_3_0001.geometry} material={materials['cacturs_3.002']} position={[-232.7, 103.095, 26.578]} rotation={[0.001, 0.113, -0.376]} scale={3.135} />
          </group>
        </group>
      </group>
      <group position={[120.123, 0, 0]} rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group position={[0, 0, -290.805]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.cactus_4_cacturs_4_0001.geometry} material={materials['cacturs_4.002']} position={[-170.753, 102.405, 20.404]} scale={4.055} />
          </group>
        </group>
      </group>
      <mesh geometry={nodes.Plane001.geometry} material={materials['Material.001']} position={[15.83, 5.642, 0.425]} scale={55.517} />
      <group scale={0.01}>
        <group position={[-3324.098, -152.913, 0]} rotation={[-1.527, -0.164, 0.131]} scale={461.257}>
          <mesh geometry={nodes.cactus_1_cacturs_1_0.geometry} material={materials['cacturs_1.001']} position={[-0.81, -6.574, 0.346]} scale={1.218} />
        </group>
        <group position={[-265.018, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.cactus_2_cacturs_2_0.geometry} material={materials['cacturs_2.001']} position={[-253.451, 38.192, 9.431]} scale={6.274} />
        </group>
        <group position={[-543.246, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.cactus_3_cacturs_3_0.geometry} material={materials['cacturs_3.001']} position={[-232.712, 103.092, 36.011]} scale={3.135} />
        </group>
        <group position={[0, 0, -290.805]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.cactus_4_cacturs_4_0.geometry} material={materials['cacturs_4.001']} position={[-170.753, 55.857, 0]} scale={5.272} />
        </group>
        <group position={[-274.491, 0, -290.805]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.cactus_5_cacturs_5_0.geometry} material={materials['cacturs_5.001']} position={[-21.144, 42.001, 7.715]} scale={6.431} />
        </group>
        <group position={[-543.488, 0, -291.646]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.cactus_6_cacturs_6_0.geometry} material={materials['cacturs_6.001']} position={[-105.949, -4.136, -0.02]} rotation={[-0.113, -0.045, -0.01]} scale={4.769} />
        </group>
        <group position={[-0.182, 0, -598.438]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.cactus_7_cacturs_7_0.geometry} material={materials['cacturs_7.001']} position={[49.312, 13.867, 0]} scale={4.601} />
        </group>
        <group position={[-267.22, 0, -598.819]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.cactus_8_cacturs_8_0.geometry} material={materials['cacturs_8.001']} position={[-218.817, -8.405, -5.651]} scale={6.334} />
        </group>
        <group position={[-553.364, 0, -598.819]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.cactus_9_cacturs_9_0.geometry} material={materials['cacturs_9.001']} position={[-77.547, 83.709, 12.001]} scale={5.288} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/teren.gltf')
